CREATE TABLE PEOPLE(
                       NAME VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
                       KEY VARCHAR_IGNORECASE(50));

CREATE TABLE ROLES(
                      NAME VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
                      ROLE VARCHAR_IGNORECASE(50) NOT NULL,
                      CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(NAME)
                          REFERENCES PEOPLE(NAME));
COMMIT;

